version: '3'
services:
    openeo-baseserver:
        build: 
            context: .
            dockerfile: DOCKERFILE-base
        image: openeo-baseserver:1.1
    openeo-rserver:
        build: 
            context: .
            dockerfile: DOCKERFILE
        image: openeo-r-backend:0.2.1
        container_name: openeo-rserver
        ports:
            - "8000:8000"
        depends_on:
            - openeo-baseserver