FROM r-base:3.5.0
MAINTAINER Florian Lahn (florian.lahn@uni-muenster.de)
LABEL version="1.5"
LABEL description="The basic configuration of the openeo r server image"

# create the path for the user files
RUN mkdir -p /opt/dockerfiles/ && mkdir -p /var/openeo/workspace/

COPY ./ /opt/dockerfiles/

# run commands to prepare the image
# install dependencies
RUN apt-get -y update && apt-get -y install libgdal-dev libcurl4-gnutls-dev libssl-dev libssh2-1-dev libsodium-dev gdal-bin libudunits2-dev

# install R dependencies and install package
RUN R --no-save -f /opt/dockerfiles/Dockerfiles/install_package_dependencies.R
