FROM openeo-baseserver:1.0
MAINTAINER Florian Lahn (florian.lahn@uni-muenster.de)
LABEL version="0.2.2"
LABEL description="A simple openeo (almost) conformant backend for frontend development"

# create the path for the user files
RUN mkdir -p /opt/dockerfiles/
RUN mkdir -p /var/openeo/workspace/
RUN mkdir -p /var/openeo/workspace/data/

RUN wget -O /var/openeo/workspace/data/openeo-demo.zip -nv https://uni-muenster.sciebo.de/s/aiAEcP6DtHQ7t2Q/download
RUN unzip -q -d /var/openeo/workspace/data/ /var/openeo/workspace/data/openeo-demo.zip

RUN rm /var/openeo/workspace/data/openeo-demo.zip

COPY ./ /opt/dockerfiles/

# install package
RUN R -f /opt/dockerfiles/Dockerfiles/install_package.R


# cmd or entrypoint for startup
ENTRYPOINT ["R", "-q", "--no-save", "-f /opt/dockerfiles/Dockerfiles/server_start.R"]

EXPOSE 8000