version: '3'
services:
    openeo-r-server:
        build: 
            context: .
            dockerfile: DOCKERFILE
        image: openeo-r-backend:0.3.1-3
        container_name: openeo-r-server
        ports:
            - "8000:8000"
        volumes:
            - openeo-r-workspace:/var/openeo/workspace/
        external_links:
            - openeo-r-mapserver:mapserver
            - openeo-r-udfserver:r-udfserver
    openeo-r-mapserver:
        image: geodata/mapserver
        container_name: openeo-r-mapserver
        volumes:
            - openeo-r-workspace:/maps/
        depends_on:
            - openeo-r-server
    openeo-r-udf-server:
        image: openeor/openeo-r-udf-server:0.0.4-2
        container_name: openeo-r-udfserver
        ports:
            - "8010:8010"

volumes:
    openeo-r-workspace: 