FROM openeo-baseserver:1.5
MAINTAINER Florian Lahn (florian.lahn@uni-muenster.de)
LABEL version="0.2.5"
LABEL description="A simple openeo (almost) conformant backend for frontend development"

# create the path for the user files
RUN mkdir -p /opt/dockerfiles/ && mkdir -p /var/openeo/workspace/

COPY ./ /opt/dockerfiles/

# install package
RUN R -f /opt/dockerfiles/Dockerfiles/install_package.R


# cmd or entrypoint for startup
ENTRYPOINT ["R", "-q", "--no-save", "-f /opt/dockerfiles/Dockerfiles/server_start.R"]

EXPOSE 8000